---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.3.1
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    grafana:
      defaultDashboardsTimezone: browser
      defaultDashboardsEditable: false
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - cloudlabs-grafana.duckdns.org
        tls:
          - secretName: cloudlabs-grafana.duckdns.org-tls
            hosts:
              - cloudlabs-grafana.duckdns.org
        annotations:
          kubernetes.io/ingress.class: traefik
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway
          jsonData:
            timeout: 60
            maxLines: 1000
    prometheus:
      prometheusSpec:
        retention: 24w
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
