---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openfga
  namespace: auth
spec:
  interval: 24h
  url: https://openfga.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: openfga
      version: "0.2.21"
      sourceRef:
        kind: HelmRepository
        name: openfga
        namespace: auth
      interval: 12h
  releaseName: openfga
  targetNamespace: auth
  values:
    authn:
      method: preshared
    extraEnvVars:
      - name: OPENFGA_AUTHN_PRESHARED_KEYS
        valueFrom:
          secretKeyRef:
            name: preshared-keys
            key: keys
    playground:
      enabled: false
    postgresql:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: cloudlabs-openfga.duckdns.org
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: cloudlabs-openfga.duckdns.org-tls
          hosts:
            - cloudlabs-openfga.duckdns.org

